import os
import threading
import tempfile
import subprocess
import shutil
from http.server import BaseHTTPRequestHandler, HTTPServer

from telegram import Update
from telegram.ext import (
    Application,
    CommandHandler,
    MessageHandler,
    ContextTypes,
    filters,
)

from telethon import TelegramClient
from telethon.sessions import StringSession


BOT_TOKEN = os.getenv("BOT_TOKEN")
API_ID = int(os.getenv("API_ID", "0"))
API_HASH = os.getenv("API_HASH")
TELEGRAM_SESSION = os.getenv("TELEGRAM_SESSION")

PORT = int(os.getenv("PORT", "10000"))

STORAGE_CHANNEL_NAME = "Cartoon Clip Storage"

telethon_client = None


class HealthHandler(BaseHTTPRequestHandler):

    def do_GET(self):
        if self.path == "/health":
            self.send_response(200)
            self.send_header("Content-Type", "text/plain")
            self.end_headers()
            self.wfile.write(b"Bot is healthy")
        else:
            self.send_response(404)
            self.end_headers()

    def log_message(self, format, *args):
        return


def start_health_server():
    server = HTTPServer(
        ("0.0.0.0", PORT),
        HealthHandler
    )
    server.serve_forever()


async def start(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE
):
    await update.message.reply_text(
        "👋 Hello!\n\n"
        "I'm your Cartoon Instagram Bot.\n\n"
        "Telegram connection is working."
    )


async def test_telegram(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE
):
    try:
        me = await telethon_client.get_me()

        name = " ".join(
            part
            for part in [me.first_name, me.last_name]
            if part
        )

        await update.message.reply_text(
            f"✅ Telethon connected!\n\n"
            f"Account: {name}\n"
            f"User ID: {me.id}"
        )

    except Exception as e:
        await update.message.reply_text(
            f"❌ Telethon connection failed:\n"
            f"{type(e).__name__}: {str(e)}"
        )


async def find_storage_channel():

    dialogs = await telethon_client.get_dialogs(
        limit=None
    )

    for dialog in dialogs:

        entity = dialog.entity

        title = getattr(
            entity,
            "title",
            None
        )

        if title == STORAGE_CHANNEL_NAME:
            return entity

    return None


async def find_source_video(
    storage_channel
):
    """
    Find the largest recent video that is NOT
    a generated [CLIP].

    This prevents the bot from accidentally
    processing one of its own generated clips.
    """

    messages = await telethon_client.get_messages(
        storage_channel,
        limit=50
    )

    source_video = None
    largest_size = 0

    for message in messages:

        if not getattr(message, "video", None):
            continue

        caption = message.message or ""

        # Ignore videos already generated by this bot
        if "[CLIP]" in caption:
            continue

        file_size = 0

        if message.file:
            file_size = message.file.size or 0

        print(
            f"Candidate video: "
            f"ID={message.id}, "
            f"size={file_size} bytes, "
            f"caption={caption!r}"
        )

        if file_size > largest_size:

            largest_size = file_size
            source_video = message

    if source_video is None:
        raise RuntimeError(
            "No source video found in storage channel."
        )

    print(
        f"Selected source video: "
        f"ID={source_video.id}, "
        f"size={largest_size} bytes"
    )

    return source_video


async def download_video(
    video_message
):

    temp_dir = tempfile.mkdtemp(
        prefix="cartoon_processing_"
    )

    input_path = os.path.join(
        temp_dir,
        f"source_{video_message.id}.mp4"
    )

    print(
        f"Downloading source video to: "
        f"{input_path}"
    )

    downloaded_file = (
        await telethon_client.download_media(
            video_message,
            file=input_path
        )
    )

    if not downloaded_file:
        raise RuntimeError(
            "Telethon failed to download the source video."
        )

    return temp_dir, downloaded_file


def split_video(
    input_path,
    output_dir
):

    output_pattern = os.path.join(
        output_dir,
        "clip_%03d.mp4"
    )

    command = [
        "ffmpeg",
        "-y",

        "-i",
        input_path,

        "-map",
        "0",

        "-c",
        "copy",

        "-f",
        "segment",

        "-segment_time",
        "40",

        "-reset_timestamps",
        "1",

        output_pattern,
    ]

    print(
        "Running FFmpeg:"
    )

    print(
        " ".join(command)
    )

    result = subprocess.run(
        command,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )

    if result.returncode != 0:

        print(
            result.stderr
        )

        raise RuntimeError(
            "FFmpeg failed to split the video."
        )

    clips = []

    for filename in sorted(
        os.listdir(output_dir)
    ):

        if filename.endswith(".mp4"):

            clips.append(
                os.path.join(
                    output_dir,
                    filename
                )
            )

    if not clips:
        raise RuntimeError(
            "FFmpeg created no clips."
        )

    return clips


async def upload_clips(
    storage_channel,
    clips
):

    uploaded_messages = []

    total_clips = len(clips)

    for index, clip_path in enumerate(
        clips,
        start=1
    ):

        clip_size = os.path.getsize(
            clip_path
        )

        clip_size_mb = (
            clip_size / (1024 * 1024)
        )

        caption = (
            f"[CLIP]\n"
            f"Clip {index}/{total_clips}\n"
            f"Source: generated by Cartoon Instagram Bot"
        )

        print(
            f"Uploading clip "
            f"{index}/{total_clips}: "
            f"{clip_size_mb:.2f} MB"
        )

        uploaded_message = (
            await telethon_client.send_file(
                storage_channel,
                clip_path,
                caption=caption,
                supports_streaming=True,
            )
        )

        uploaded_messages.append(
            uploaded_message
        )

        print(
            f"Uploaded clip "
            f"{index}/{total_clips} "
            f"with message ID "
            f"{uploaded_message.id}"
        )

    return uploaded_messages


async def process_and_upload_test(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE
):

    processing_dir = None

    try:

        await update.message.reply_text(
            "📦 Opening Cartoon Clip Storage..."
        )

        storage_channel = (
            await find_storage_channel()
        )

        if storage_channel is None:
            raise RuntimeError(
                f'Could not find "{STORAGE_CHANNEL_NAME}".'
            )

        await update.message.reply_text(
            "🔎 Finding source video..."
        )

        source_video = (
            await find_source_video(
                storage_channel
            )
        )

        source_size = (
            source_video.file.size
            if source_video.file
            else 0
        )

        source_size_mb = (
            source_size / (1024 * 1024)
        )

        await update.message.reply_text(
            "✅ Source video found!\n\n"
            f"Message ID: {source_video.id}\n"
            f"Size: {source_size_mb:.2f} MB\n\n"
            "⬇️ Downloading..."
        )

        processing_dir, input_path = (
            await download_video(
                source_video
            )
        )

        await update.message.reply_text(
            "✅ Video downloaded!\n\n"
            "✂️ Splitting into 40-second clips..."
        )

        clips_dir = os.path.join(
            processing_dir,
            "clips"
        )

        os.makedirs(
            clips_dir,
            exist_ok=True
        )

        clips = split_video(
            input_path,
            clips_dir
        )

        await update.message.reply_text(
            f"✂️ FFmpeg created "
            f"{len(clips)} clips.\n\n"
            "⬆️ Uploading clips to "
            "Cartoon Clip Storage..."
        )

        uploaded_messages = (
            await upload_clips(
                storage_channel,
                clips
            )
        )

        result_lines = [
            "🎉 CLIP UPLOAD TEST SUCCESSFUL!",
            "",
            f"🎬 Source message: {source_video.id}",
            f"✂️ Clips created: {len(clips)}",
            "",
            "Uploaded Telegram messages:"
        ]

        for index, message in enumerate(
            uploaded_messages,
            start=1
        ):

            result_lines.append(
                f"Clip {index}: "
                f"Message ID {message.id}"
            )

        result_lines.extend([
            "",
            "✅ Clips are now stored in "
            "Cartoon Clip Storage."
        ])

        await update.message.reply_text(
            "\n".join(result_lines)
        )

    except Exception as e:

        print(
            f"PROCESSING ERROR: "
            f"{type(e).__name__}: {str(e)}"
        )

        await update.message.reply_text(
            "❌ CLIP UPLOAD TEST FAILED\n\n"
            f"Error: {type(e).__name__}\n"
            f"Details: {str(e)}"
        )

    finally:

        if processing_dir:

            try:

                if os.path.exists(
                    processing_dir
                ):

                    shutil.rmtree(
                        processing_dir
                    )

                    print(
                        "Temporary processing "
                        "directory deleted."
                    )

            except Exception as cleanup_error:

                print(
                    f"Cleanup warning: "
                    f"{type(cleanup_error).__name__}: "
                    f"{str(cleanup_error)}"
                )


async def handle_video(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE
):

    if not update.message or not update.message.video:
        return

    await update.message.reply_text(
        "📥 Video received!\n\n"
        "Video processing will be added next."
    )


def main():

    global telethon_client

    if not BOT_TOKEN:
        raise RuntimeError(
            "BOT_TOKEN is missing."
        )

    if not API_ID:
        raise RuntimeError(
            "API_ID is missing."
        )

    if not API_HASH:
        raise RuntimeError(
            "API_HASH is missing."
        )

    if not TELEGRAM_SESSION:
        raise RuntimeError(
            "TELEGRAM_SESSION is missing."
        )

    # Start Render health server
    health_thread = threading.Thread(
        target=start_health_server,
        daemon=True,
    )

    health_thread.start()

    # Start Telethon
    telethon_client = TelegramClient(
        StringSession(TELEGRAM_SESSION),
        API_ID,
        API_HASH,
    )

    telethon_client.start()

    print(
        "Telethon connected successfully."
    )

    # Start Telegram Bot API
    app = Application.builder().token(
        BOT_TOKEN
    ).build()

    app.add_handler(
        CommandHandler(
            "start",
            start
        )
    )

    app.add_handler(
        CommandHandler(
            "test_telegram",
            test_telegram
        )
    )

    app.add_handler(
        CommandHandler(
            "process_upload_test",
            process_and_upload_test
        )
    )

    app.add_handler(
        MessageHandler(
            filters.VIDEO,
            handle_video,
        )
    )

    print(
        f"Bot is running. "
        f"Health server listening on port {PORT}."
    )

    app.run_polling()


if __name__ == "__main__":
    main()
